apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-upload-config
  labels:
    app.kubernetes.io/name: kairos-operator-nginx
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        client_max_body_size 0;
        location / {
            autoindex on;
            autoindex_exact_size off;
            autoindex_format html;
            dav_methods PUT;
            create_full_put_path on;
            dav_access user:rw group:rw all:r;
        }
    }
