apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: kairos-operator-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kairos-operator-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kairos-operator-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-public
          - mountPath: "/etc/nginx/conf.d/default.conf"
            name: nginx-upload-config
            subPath: default.conf
        ports:
          - containerPort: 80
      terminationGracePeriodSeconds: 10
      volumes:
        - name: nginx-public
          persistentVolumeClaim:
            claimName: nginx-public
        - name: nginx-upload-config
          configMap:
            name: nginx-upload-config
