apiVersion: v1
kind: Service
metadata:
  name: kairos-operator-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kairos-operator-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
