apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

# Override the image patch from default to use controller:latest
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: controller:latest
  target:
    kind: Deployment
    name: kairos-operator

images:
- name: controller
  newName: controller
  newTag: latest
